version: 2

sources:
  - name: course18
    tables:
      - name: raw_product
        identifier: raw_gz_product
      - name: raw_ship
        identifier: raw_gz_ship
      - name: raw_sales
        identifier: raw_gz_sales
