version: 2

sources:
  - name: raw
    schema: course18
    tables:
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship
      - name: sales
        identifier: raw_gz_sales
