version: 2

sources:
  - name: raw
    schema: course18
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
              - unique
             
      - name: ship
        identifier: raw_gz_ship
      - name: sales
        identifier: raw_gz_sales
        columns:
          - name: "(pdt_id||'-'||orders_id)"
        tests:
          - unique:
              column_name: "(pdt_id||'-'||orders_id)"
