version: 2

sources:
  - name: raw
    schema: course18
    description: greenweez raw data source
    tables:
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
      - name: sales
        identifier: raw_gz_sales
        columns:
          - name: "(pdt_id||'-'||orders_id)"
            tests:
              - unique
              - not_null
          - name: date_date
            freshness:
              warn_after: { count: 50, period: day }
              error_after: { count: 95, period: day }
              loaded_at_field: "CAST(date_date as TIMESTAMP)"
models:
  - name: stg_raw__product
  - name: stg_raw__sales
  - name: stg_raw__ship
  - name: int_sales_margin
  - name: int_orders_margin
  - name: int_orders_operational
  - name: finance_days